name: Format check

on:
  pull_request:
  workflow_dispatch:
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-06-13
          override: true
          components: rustfmt

      - run: cargo fmt --check
