name: Lint

on:
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-06-13
          override: true
          components: clippy

      - run: cargo +nightly-2024-06-13 clippy -- --allow async-fn-in-trait --deny warnings
  unused-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-06-13
          override: true
          components: clippy

      - run: cargo +nightly-2024-06-13 install cargo-binstall@1.6.9
      - run: cargo +nightly-2024-06-13 binstall --no-confirm cargo-udeps --locked
      - run: cargo +nightly-2024-06-13 udeps
